services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spatial_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT:-3000}
        - BACKEND_BASE_URL=${BACKEND_BASE_URL:-http://localhost:8080/v1}
    container_name: spatial_frontend
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
